modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/dark-paintings/issues"

[[mods]]
modId="darkpaintings"
updateJSONURL="https://updates.blamejared.com/get?n=darkpaintings&gv=1.15.2"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.darkpaintings]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.darkpaintings]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.darkpaintings]]
    modId="bookshelf"
    mandatory=true
    versionRange="[5.3,)"
    ordering="AFTER"
    side="BOTH"