modLoader = "javafml"
license = "LGPL v2.1"
issueTrackerURL = "https://github.com/Darkhax-Minecraft/dark-paintings/issues"

[[mods]]
modId = "darkpaintings"
version = "26.2.0.0"
displayName = "DarkPaintings"
updateJSONURL = "https://updates.blamejared.com/get?n=darkpaintings&gv=26.2&ml=neoforge"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/dark-paintings"
logoFile = "logo_darkpaintings.png"
logoBlur = false
credits = "This project is made possible with Patreon support from players like you. Thank you! lothrazar, techsquirrel, Keyana , Darkosto, Tobias Ward, noobanidus"
authors = "Darkhax"
description = "Adds a variety of new paintings to the game."

[[mixins]]
config = "darkpaintings.common.mixins.json"

[[mixins]]
config = "darkpaintings.neoforge.mixins.json"

[[dependencies.darkpaintings]]
modId = "minecraft"
type = "required"
versionRange = "26.2"
ordering = "NONE"
side = "BOTH"

[[dependencies.darkpaintings]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0.1-beta,)"
ordering = "NONE"
side = "BOTH"

